FROM eclipse-temurin:26-jdk AS build

WORKDIR /app
COPY . .
RUN chmod +x mvnw && ./mvnw -DskipTests clean package

FROM eclipse-temurin:26-jre

WORKDIR /app
COPY --from=build /app/target/mjodheim-brewstead-0.0.1-SNAPSHOT.jar app.jar

ENV PORT=8080
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
